# Generated by Django 5.1 on 2024-08-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='mo_ta',
        ),
        migrations.AlterField(
            model_name='sach',
            name='tac_gia',
            field=models.CharField(max_length=200),
        ),
    ]
