# Generated by Django 5.1 on 2024-09-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_sach_mo_ta_alter_sach_tac_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuong',
            name='so_chuong',
        ),
        migrations.AddField(
            model_name='sach',
            name='the_loai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
